# Archivo de configuración para pruebas. 
paths:
  sandbx : C:\\Users\\Aldo Quintal\\Documents\\Sandbx\\
  workng : C:\\Users\\Aldo Quintal\\Documents\\2-Workng\\
  clients : C:\\Users\\Aldo Quintal\\Clients
  path : C:\Users\Aldo Quintal\Documents\Sandbx/
  pathImp : C:/Users/Aldo Quintal/Clients

# [MySqlbd]
# host = 127.0.0.1
# user = root
# password = 1234